// CREAR UNA PROMESA Y CONSUMIRLA PARA LLEVARLE UN HELADO A UN AMIGO SI LA HELADERIA ESTA ABIERTA 

let heladeriaAbierta = false
// FORMAS DE USAR PROMESAS 
// 1. CREAR LAS REGLAS DE LA PROMESA . NOS PUEDE TOCAR HACERLO O NO 
promise(function(resolve,reject){}